const roles = [
  ["Research Assisted — Undergraduate Specialist", "Assist undergraduate students with topic refinement, proposal/project structure, literature discovery and organization, research instruments, citation checks, proofreading, formatting and supervisor corrections under QA supervision."],
  ["Research Assisted — Postgraduate Specialist", "Support postgraduate researchers with advanced literature-search workflows, conceptual/theoretical framework organization, methodology guidance, verified-source management, research instruments, results presentation and supervisor corrections. Requires advanced screening."],
  ["Literature & Citation Researcher", "Find and organize relevant scholarly sources, verify bibliographic details, support APA/Harvard/MLA references and maintain source-traceability records."],
  ["Academic Formatting Assistant", "Format Word documents, projects, theses, references and tables using approved client instructions and institutional presets."],
  ["Data Analysis Assistant", "Assist with Excel/SPSS data preparation, coding, tables, charts and interpretation guidance where competence has been verified."],
  ["Printing & Production Assistant", "Prepare print jobs, check page order, support binding, packaging and quality control."],
  ["Campus Delivery Partner", "Collect and deliver completed orders across approved UNN campus zones with proof of delivery."],
  ["Customer Support & Sales Partner", "Respond to enquiries, explain services, follow up orders and earn approved referral commissions."],
];

const stages = ["Apply online", "Identity & UNN status verification", "Education/skills screening", "Role-specific practical test", "Research-integrity and source-verification test for research roles", "Structured interview", "Reference/guarantor check where required", "Confidentiality, privacy and academic-integrity orientation", "Supervised probationary assignments", "QA review and activation into approved worker pool"];

export default function WorkWithUsPage() {
  return <main className="container" style={{paddingTop:40,paddingBottom:60}}>
    <span className="badge">UNN Student Work Programme</span><h1>Earn part-time. Build real research and digital experience.</h1>
    <p className="lead">Mabrig ICT & Academic Assistance recruits capable University of Nigeria students and approved specialists for flexible roles supporting undergraduate and postgraduate research, academic document services, data support, production and campus operations.</p>
    <section className="section"><h2>Available talent pools</h2><div className="grid">{roles.map(([title,text]) => <article className="card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section"><h2>Research Assisted recruitment standard</h2><div className="card"><ul><li>Undergraduate research assistants should demonstrate strong academic writing, source discovery, citation and document-organization skills.</li><li>Postgraduate research specialists should normally demonstrate postgraduate-level research competence or equivalent verified experience.</li><li>Literature/citation specialists must demonstrate source verification and accurate referencing using a practical test.</li><li>Data-analysis assistants must pass a role-specific test before receiving client datasets.</li><li>Research workers must distinguish verified evidence from unsupported claims and must never fabricate references, results, respondents or data.</li><li>All client research files are confidential and access is limited to assigned tasks.</li></ul></div></section>
    <section className="section"><h2>Minimum standard</h2><div className="card"><ul><li>Current UNN student or other specifically approved applicant.</li><li>Reliable phone number and email address.</li><li>Good communication, punctuality and respect for client confidentiality.</li><li>Role-relevant competence demonstrated through practical testing.</li><li>Agreement to academic-integrity, privacy, quality-control and anti-fraud rules.</li><li>Declared availability that does not interfere with classes or examinations.</li></ul></div></section>
    <section className="section"><h2>Recruitment process</h2><div className="card"><ol>{stages.map(stage => <li key={stage}>{stage}</li>)}</ol><p><strong>No recruitment fee:</strong> applicants are not charged to apply, interview or receive a legitimate work offer.</p></div></section>
    <section className="section"><h2>Research-role practical test</h2><div className="grid"><article className="card"><h3>Source verification</h3><p>Locate sample scholarly sources and accurately capture author, year, title, journal/publisher and DOI or stable link where available.</p></article><article className="card"><h3>Research structure</h3><p>Organize a dummy research problem into objectives, questions, literature themes and an appropriate methodological outline without inventing evidence.</p></article><article className="card"><h3>Editing & citation</h3><p>Correct a sample academic passage, preserve meaning, identify citation problems and produce clean references.</p></article><article className="card"><h3>Integrity test</h3><p>Identify fabricated citations, unsupported claims and improper research practices before handling live client work.</p></article></div></section>
    <section className="section"><h2>How workers earn</h2><div className="grid"><article className="card"><h3>Task pay</h3><p>Approved rate per research-support, formatting, production, data or delivery task, shown before acceptance.</p></article><article className="card"><h3>Specialist rate</h3><p>Advanced postgraduate research, citation verification, QA and data-analysis tasks can carry higher approved specialist rates.</p></article><article className="card"><h3>Referral commission</h3><p>Eligible partners receive defined commissions after qualifying customer orders are paid and verified.</p></article><article className="card"><h3>Performance bonus</h3><p>Optional bonuses reward sustained quality, reliability, verified-source accuracy and low rework rates.</p></article></div></section>
    <section className="section"><h2>Worker protections & research integrity</h2><div className="card"><p>Every engagement states the task, pay basis, turnaround, supervisor, confidentiality duties and dispute channel. Research Assisted is tutoring, research guidance, editing, source support, data-analysis guidance and legitimate academic assistance. Workers must not impersonate students, fabricate research, complete examinations or misrepresent ghostwritten assessed work as a student's own work.</p></div></section>
    <section className="section"><div className="notice"><strong>Application dashboard fields:</strong> full name, UNN registration number where applicable, faculty/department, programme/degree level, research areas, software skills, citation styles, data-analysis skills, availability, portfolio/sample, preferred role, practical-test scores, verification status, QA level and payout status.</div></section>
  </main>;
}
